# motion simulator

**ver 1**

- implement the input section
- implement processing
- output: print out array of points

In [1]:
# numerical python library for fast numerical vector & matrix calculations
import numpy as np

#### input

In [6]:
# number of time steps
N = 100

# set time step
dt = 0.1

# define func for trajectory
# input - time t
# output - position vector
def trajectory(t):
    # linear motion w/ velocity (1, 1)
    return np.array([t,t])

#initalize variables
t=0
points = np.zeros((N+1,2))

In [7]:
points[0]

array([0., 0.])

#### processing

In [8]:
# calculate N points on trajectory for times w time step dt apart

for i in range(N):
    # call function trajectory w current time t
    # save new point in array points
    # update time
    points[i] = trajectory(t)
    t += dt

In [9]:
points

array([[0. , 0. ],
       [0.1, 0.1],
       [0.2, 0.2],
       [0.3, 0.3],
       [0.4, 0.4],
       [0.5, 0.5],
       [0.6, 0.6],
       [0.7, 0.7],
       [0.8, 0.8],
       [0.9, 0.9],
       [1. , 1. ],
       [1.1, 1.1],
       [1.2, 1.2],
       [1.3, 1.3],
       [1.4, 1.4],
       [1.5, 1.5],
       [1.6, 1.6],
       [1.7, 1.7],
       [1.8, 1.8],
       [1.9, 1.9],
       [2. , 2. ],
       [2.1, 2.1],
       [2.2, 2.2],
       [2.3, 2.3],
       [2.4, 2.4],
       [2.5, 2.5],
       [2.6, 2.6],
       [2.7, 2.7],
       [2.8, 2.8],
       [2.9, 2.9],
       [3. , 3. ],
       [3.1, 3.1],
       [3.2, 3.2],
       [3.3, 3.3],
       [3.4, 3.4],
       [3.5, 3.5],
       [3.6, 3.6],
       [3.7, 3.7],
       [3.8, 3.8],
       [3.9, 3.9],
       [4. , 4. ],
       [4.1, 4.1],
       [4.2, 4.2],
       [4.3, 4.3],
       [4.4, 4.4],
       [4.5, 4.5],
       [4.6, 4.6],
       [4.7, 4.7],
       [4.8, 4.8],
       [4.9, 4.9],
       [5. , 5. ],
       [5.1, 5.1],
       [5.2,

#### output

test

below, numpy.ndarray, d stands for double

In [2]:
arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>
